import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {type: 'doc', id: 'index', label: 'Welcome to Adri AI Docs'},
    {type: 'doc', id: 'use-adri-for-free', label: 'Use Adri for Free'},
    {
      type: 'category',
      label: 'Project Management',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'project-management'}],
    },
    {
      type: 'category',
      label: 'Connect SAP System',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'connect-sap-system'}],
    },
    {
      type: 'category',
      label: 'Adri MCP Server',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'adri-mcp-server'}],
    },
    {
      type: 'category',
      label: 'Code Agent',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'code-agent'}],
    },
    {
      type: 'category',
      label: 'SAP Research Agent',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'research-agent'}],
    },
    {
      type: 'category',
      label: 'Deploying Adri in Enterprise',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'enterprise-deployment'}],
    },
    {
      type: 'category',
      label: 'AI Concepts',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'ai-concepts'}],
    },
    {
      type: 'category',
      label: 'Glossary',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'glossary'}],
    },
    {
      type: 'category',
      label: 'Comparisons',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'comparisons'}],
    },
    {type: 'doc', id: 'faqs'},
    {type: 'doc', id: 'contact'},
  ],
};

export default sidebars;
